### PR TITLE
created secret for atlantis via docker

### PR DESCRIPTION
**Pull request by Gopirengarajmm**

### CODE REVIEW

**Comment by KarthikaSadaiyappan** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_secretsmanager_secret.terraform_test_docker will be created
+ resource "aws_secretsmanager_secret" "terraform_test_docker" {
      + arn                            = (known after apply)
      + force_overwrite_replica_secret = false
      + id                             = (known after apply)
      + name                           = "terraform_test_docker"
      + name_prefix                    = (known after apply)
      + policy                         = (known after apply)
      + recovery_window_in_days        = 30
      + rotation_enabled               = (known after apply)
      + rotation_lambda_arn            = (known after apply)
      + tags_all                       = (known after apply)
    }

  # aws_secretsmanager_secret.terraform_test_ecs will be created
+ resource "aws_secretsmanager_secret" "terraform_test_ecs" {
      + arn                            = (known after apply)
      + force_overwrite_replica_secret = false
      + id                             = (known after apply)
      + name                           = "terraform_test1"
      + name_prefix                    = (known after apply)
      + policy                         = (known after apply)
      + recovery_window_in_days        = 30
      + rotation_enabled               = (known after apply)
      + rotation_lambda_arn            = (known after apply)
      + tags_all                       = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://ec2-13-235-121-243.ap-south-1.compute.amazonaws.com:4141/lock?id=AthivaTechnology%252Fatalntis-terraform%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 2 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by Gopirengarajmm** [comment]
atlantis apply

**Comment by KarthikaSadaiyappan** [comment]
Ran Apply for dir: `.` workspace: `default`

**Apply Error**
```
running "/usr/local/bin/terraform apply -input=false \"/home/atlantis/.atlantis/repos/AthivaTechnology/atalntis-terraform/5/default/default.tfplan\"" in "/home/atlantis/.atlantis/repos/AthivaTechnology/atalntis-terraform/5/default": exit status 1
aws_secretsmanager_secret.terraform_test_ecs: Creating...
aws_secretsmanager_secret.terraform_test_docker: Creating...
aws_secretsmanager_secret.terraform_test_docker: Creation complete after 0s [id=arn:aws:secretsmanager:ap-south-1:301838289846:secret:terraform_test_docker-FOvjZ8]
╷
│ Error: error creating Secrets Manager Secret: ResourceExistsException: The operation failed because the secret terraform_test1 already exists.
│ 
│   with aws_secretsmanager_secret.terraform_test_ecs,
│   on s3.tf line 15, in resource "aws_secretsmanager_secret" "terraform_test_ecs":
│   15: resource "aws_secretsmanager_secret" "terraform_test_ecs" {
│ 
╵

```

**Comment by KarthikaSadaiyappan** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
- destroy
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # aws_secretsmanager_secret.terraform_test must be replaced
-/+ resource "aws_secretsmanager_secret" "terraform_test" {
      ~ arn                            = "arn:aws:secretsmanager:ap-south-1:301838289846:secret:terraform_test-889xI8" -> (known after apply)
      ~ id                             = "arn:aws:secretsmanager:ap-south-1:301838289846:secret:terraform_test-889xI8" -> (known after apply)
      ~ name                           = "terraform_test" -> "terraform_test_v3" # forces replacement
      + name_prefix                    = (known after apply)
      + policy                         = (known after apply)
      ~ rotation_enabled               = false -> (known after apply)
      + rotation_lambda_arn            = (known after apply)
      - tags                           = {} -> null
      ~ tags_all                       = {} -> (known after apply)
        # (2 unchanged attributes hidden)
    }

  # aws_secretsmanager_secret.terraform_test1 will be destroyed
  # (because aws_secretsmanager_secret.terraform_test1 is not in configuration)
- resource "aws_secretsmanager_secret" "terraform_test1" {
      - arn                            = "arn:aws:secretsmanager:ap-south-1:301838289846:secret:terraform_test1-oz18I6" -> null
      - force_overwrite_replica_secret = false -> null
      - id                             = "arn:aws:secretsmanager:ap-south-1:301838289846:secret:terraform_test1-oz18I6" -> null
      - name                           = "terraform_test1" -> null
      - recovery_window_in_days        = 30 -> null
      - rotation_enabled               = false -> null
      - tags                           = {} -> null
      - tags_all                       = {} -> null
    }

  # aws_secretsmanager_secret.terraform_test_docker will be destroyed
  # (because aws_secretsmanager_secret.terraform_test_docker is not in configuration)
- resource "aws_secretsmanager_secret" "terraform_test_docker" {
      - arn                            = "arn:aws:secretsmanager:ap-south-1:301838289846:secret:terraform_test_docker-FOvjZ8" -> null
      - force_overwrite_replica_secret = false -> null
      - id                             = "arn:aws:secretsmanager:ap-south-1:301838289846:secret:terraform_test_docker-FOvjZ8" -> null
      - name                           = "terraform_test_docker" -> null
      - recovery_window_in_days        = 30 -> null
      - rotation_enabled               = false -> null
      - tags                           = {} -> null
      - tags_all                       = {} -> null
    }

Plan: 1 to add, 0 to change, 3 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://ec2-13-235-121-243.ap-south-1.compute.amazonaws.com:4141/lock?id=AthivaTechnology%252Fatalntis-terraform%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 1 to add, 0 to change, 3 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by Gopirengarajmm** [comment]
atlantis apply

**Comment by KarthikaSadaiyappan** [comment]
Ran Apply for dir: `.` workspace: `default`

```diff
aws_secretsmanager_secret.terraform_test: Destroying... [id=arn:aws:secretsmanager:ap-south-1:301838289846:secret:terraform_test-889xI8]
aws_secretsmanager_secret.terraform_test1: Destroying... [id=arn:aws:secretsmanager:ap-south-1:301838289846:secret:terraform_test1-oz18I6]
aws_secretsmanager_secret.terraform_test_docker: Destroying... [id=arn:aws:secretsmanager:ap-south-1:301838289846:secret:terraform_test_docker-FOvjZ8]
aws_secretsmanager_secret.terraform_test: Destruction complete after 0s
aws_secretsmanager_secret.terraform_test: Creating...
aws_secretsmanager_secret.terraform_test_docker: Destruction complete after 0s
aws_secretsmanager_secret.terraform_test1: Destruction complete after 0s
aws_secretsmanager_secret.terraform_test: Creation complete after 0s [id=arn:aws:secretsmanager:ap-south-1:301838289846:secret:terraform_test_v3-ZT73wr]

Apply complete! Resources: 1 added, 0 changed, 3 destroyed.
```

**Comment by KarthikaSadaiyappan** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by KarthikaSadaiyappan** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
